@Sample.Api_HostAddress = http://localhost:5157

// A sample endpoint to check if the Api is running
GET {{Sample.Api_HostAddress}}/sample/today

###

// Without Api Key the request should be rejected
GET {{Sample.Api_HostAddress}}/sample/details

###

// The authentication should work providing a valid Api Key
GET {{Sample.Api_HostAddress}}/sample/details
X-Api-Key: S7hZ6DeKmqpUWVELawt8gR2bHc3NM9vn

###

GET {{Sample.Api_HostAddress}}/sample/details
X-Api-Key: UQSaqtdMPkc3XhDKb74x65CAYEemvZ8R

##